// ------------------------------------------------------------------------------
// <auto-generated>
// Dieser Code wurde von einem Tool generiert.
// Laufzeitversion:4.0.30319.42000
// 
// Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
// der Code erneut generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using Microsoft.VisualBasic;

namespace POFF.Kicker.Model.My.Resources
{

    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    /// <summary>
    /// Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("POFF.Kicker.Model.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        /// Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die &lt;p&gt;&lt;!-- Stand --&gt;&lt;/p&gt;
        ///                    &lt;table class=&quot;table table-striped&quot;&gt;
        ///                        &lt;thead&gt;
        ///                        &lt;tr&gt;
        ///                            &lt;th&gt;Platz&lt;/th&gt;
        ///                            &lt;th&gt;Spieler&lt;/th&gt;
        ///                            &lt;th&gt;Spiele&lt;/th&gt;
        ///                            &lt;th&gt;Punkte&lt;/th&gt;
        ///                            &lt;th&gt;Frames&lt;/th&gt;
        ///                        &lt;/tr&gt;
        ///                        &lt;/thead&gt;
        ///                        &lt;tbody&gt;
        /// &lt;!-- Tabelle --&gt;
        ///                        &lt;/tb [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HtmlExportStandingOnlyTemplate
        {
            get
            {
                return ResourceManager.GetString("HtmlExportStandingOnlyTemplate", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die {% extends &apos;base.html.twig&apos; %}
        /// 
        /// {% block title %}Club-Liga 2022/23{% endblock %}
        /// 
        /// {% block body %}
        ///    &lt;div class=&quot;club&quot;&gt;
        ///        &lt;div class=&quot;container main-container&quot;&gt;
        ///            &lt;div class=&quot;row&quot;&gt;
        ///                &lt;div class=&quot;col-md-12 mt-12&quot;&gt;
        ///                    &lt;h1&gt;Club-Liga 2022/23&lt;/h1&gt;
        ///                    &lt;p&gt;&lt;!-- Stand --&gt;&lt;/p&gt;
        ///                    &lt;table class=&quot;table table-striped&quot;&gt;
        ///                        &lt;thead&gt;
        ///                        &lt;tr&gt;
        ///                            &lt;th&gt;Platz&lt;/th&gt;
        ///    [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string HtmlExportTemplate
        {
            get
            {
                return ResourceManager.GetString("HtmlExportTemplate", resourceCulture);
            }
        }
    }
}